### ISSUE TITLE
Exterior -> Trunk -> Changes camera to "random" position?

### ISSUE THREAD

**Issue by SumnDaiy** [renzuzu/renzu_customs#13]
https://streamable.com/1v9h4r

**Comment by SumnDaiy** [comment]
Also happens with "hood" option

**Comment by SumnDaiy** [comment]
And with "horn"

**Comment by renzuzu** [comment]
can i get teh vehicle model?
it seems trunk needs to be a fixed camera instead of bone camera option.

bonnet has been fixed earlier.

EDIT:
added camera option to some boot bone default (causing camera glitch):
https://github.com/renzuzu/renzu_customs/commit/ff5b3571d7431cad2c66dc51ceeec859d052b50c
